"""Shared domain enumerations."""

from __future__ import annotations

from enum import Enum


class DroneRole(str, Enum):
    """Mission role of a drone. LEADER may issue privileged COMMAND packets."""

    LEADER = "leader"
    WORKER = "worker"
    RELAY = "relay"


class AuthState(str, Enum):
    """Authentication lifecycle of a drone (as seen by the network)."""

    UNREGISTERED = "unregistered"
    REGISTERED = "registered"  # provisioned by the control server, no session yet
    AUTHENTICATED = "authenticated"  # holds at least one valid D2DAP session
    REAUTH_PENDING = "reauth_pending"  # sessions revoked, must run MAKA again
    AUTH_FAILED = "auth_failed"
    REVOKED = "revoked"


class SecurityState(str, Enum):
    """Adaptive-policy state (our contribution, Phase 13). Ordered by severity."""

    NORMAL = "normal"
    MONITOR = "monitor"
    RESTRICT = "restrict"
    REAUTHENTICATE = "reauthenticate"
    QUARANTINE = "quarantine"

    @property
    def severity(self) -> int:
        return _SEVERITY[self]


_SEVERITY = {
    SecurityState.NORMAL: 0,
    SecurityState.MONITOR: 1,
    SecurityState.RESTRICT: 2,
    SecurityState.REAUTHENTICATE: 3,
    SecurityState.QUARANTINE: 4,
}


class PacketProtocol(str, Enum):
    """Application/protocol type carried by a simulated packet."""

    TELEMETRY = "telemetry"  # periodic state reports (MAVLink-like)
    VIDEO = "video"  # bursty payload stream
    COMMAND = "command"  # control commands (privileged: leader only)
    HEARTBEAT = "heartbeat"  # neighbour keep-alive
    AUTH_REQUEST = "auth_request"  # D2DAP M1 {CM, sigma1, sigma2}
    AUTH_RESPONSE = "auth_response"  # D2DAP M2 {DM, sigma3, sigma4}
    RL_BROADCAST = "rl_broadcast"  # D2DAP revocation-list update
    TRUST_REPORT = "trust_report"  # observation report to the security monitor (ours)
    POLICY_NOTICE = "policy_notice"  # quarantine / restriction notice (ours)


#: Protocols generated by the security machinery itself (counted as overhead).
CONTROL_PLANE = frozenset(
    {
        PacketProtocol.AUTH_REQUEST,
        PacketProtocol.AUTH_RESPONSE,
        PacketProtocol.RL_BROADCAST,
        PacketProtocol.TRUST_REPORT,
        PacketProtocol.POLICY_NOTICE,
    }
)

BENIGN_LABEL = "benign"
BROADCAST = "*"
